# Site settings
title: Prasanth's Blog
header-img: img/home-bg.jpg
email: prasanthmani2010@gmail.com
description: "my record of my path in open source life"
baseurl: ""
url: "http://foxprasanth.github.io/"
twitter_username: prasanthp96
github_username:  prasanthp96
facebook_username:  prasanthp96

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 9
paginate_path: "/blog/page:1/"
exclude: ["less","node_modules"	,"Gruntfile.js","package.json","README.md"]
